apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: autograder
  region: us-east-1
  version: "1.23"
managedNodeGroups:
- name: t2-micro-nodes
  instanceType: t2.micro
  desiredCapacity: 1
  minSize: 1
  maxSize: 3
  volumeSize: 20 
