apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: autograder
  region: eu-west-3
  version: "1.24"
managedNodeGroups:
- name: primary
  instanceType: t3.small
  desiredCapacity: 1
  minSize: 1
  maxSize: 3
  volumeSize: 20 
