apiVersion: v1
kind: ConfigMap
metadata:
  name: cwagentconfig
  namespace: amazon-cloudwatch
  labels:
    app: cloudwatch
data:
  cwagentconfig.json: |
    {
      "metrics": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "autograder",
            "metrics_collection_interval": 60,
            "measurement": [
              "node_cpu_utilization",
              "node_memory_utilization",
              "pod_cpu_utilization",
              "pod_memory_utilization",
              "node_network_total_bytes"
            ]
          }
        }
      },
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/containers/*.log",
                "log_group_name": "projet-master-eks/logs",
                "log_stream_name": "{pod_name}",
                "timezone": "UTC"
              }
            ]
          }
        }
      }
    }
