apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: autograder
    role: frontend  # Assurez-vous que cela correspond au label du pod
  ports:
  - protocol: TCP
    port: 80        # Port du service
    targetPort: 80  # Port du conteneur
  type: LoadBalancer  # Changez le type en LoadBalancer
