apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    # Activer HTTPS sur le Load Balancer AWS
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account:certificate/certificate-id"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

spec:
  selector:
    app: autograder
    role: frontend  # Assurez-vous que cela correspond au label du pod
  ports:
  - port: 443
    targetPort: 80
    protocol: TCP
  type: LoadBalancer  # Changez le type en LoadBalancer
