apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: autograder
spec:
  selector:
    app: autograder
    role: frontend  # Assurez-vous que cela correspond au label du pod
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
