apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc  # Nom du PersistentVolumeClaim
spec:
  accessModes:
    - ReadWriteOnce  # Mode d'accès
  resources:
    requests:
      storage: 1Gi  # Capacité demandée
  storageClassName: standard  # Classe de stockage
