apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-pod
  template:
    metadata:
      labels:
        app: mongodb-pod
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}  # Utilisation des secrets
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}  # Utilisation des secrets
        volumeMounts:
          - mountPath: /data/db
            name: mongo-data
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: host-pvc
